author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /black-jacob-test-2022-02-25
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - openseadragon.min.js
    - openseadragon-svg-overlay.js
    - text-annotations.js
    - viewer.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://loris.library.emory.edu/fedora:emory:gnfvk/full/full/0/default.jpg
image_size:
  page:
    height: 1349
    width: 1875
permalink: pretty
publication_info:
  date: '2022'
  editors: []
  title: Black Jacob," a monument of grace the life of Jacob Hodges, an African Negro,
    who died in Canandaigua, N.Y., February 1842 /
show_annotation_author: true
source_info:
  title: Black Jacob," a monument of grace the life of Jacob Hodges, an African Negro,
    who died in Canandaigua, N.Y., February 1842 /
  via_readux: true
tagline: an annotated digital edition
title: Black Jacob," a monument of grace the life of Jacob Hodges, an African Negro,
  who died in Canandaigua, N.Y., February 1842 /
url: https://sarepal.github.io
version: 0.7
